name = "Voronoi_Combat"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef0123456789"
authors = [
  "Cemal Hekim <cemal.hekim@campus.tu-berlin.de>",
  "Andrè Neumann <>",
  "Dicle Can <>"
]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5a83-b7ef-3f447aa82063"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"